services:
  # 1. La Base de données
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3306:3306"

  # 2. Le Broker MQTT
  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  # 3. Ton serveur Node.js (Dev 2)
  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - NODE_ENV=development
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - MQTT_URL=${MQTT_URL}
    command: sh -c "npm install --include=dev && npm run dev"
    volumes:
      - ./backend:/app
      - /app/node_modules # Evite d'écraser les modules du container
    depends_on:
      - db
      - mosquitto

  # 4. Ton App React (Dev 3)
  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      - NODE_ENV=development
      - FRONTEND_PORT=${FRONTEND_PORT}
    volumes:
      - ./frontend:/app
      - /app/node_modules